# Generated by Django 4.1.4 on 2022-12-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_news_likes_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(related_name='category_news', to='blog.category'),
        ),
    ]
